### ISSUE TITLE
BSD-3-Clause license missing

### ISSUE THREAD

**Issue by slp** [cloud-hypervisor/vhost-user-backend#7]
I've just noticed this crate is just licensed as Apache-2.0, while Cloud Hypervisor has an hybrid Apache-2.0+BSD-3-Clause licensing model.

Was this done on purpose or just something coming from the crate template?

**Comment by slp** [comment]
@rbradford @sameo ping?

**Comment by rbradford** [comment]
This code was newly written so wouldn't be covered by the BSD-3-Clause code coming (originally) from crosvm

**Comment by slp** [comment]
Hmm.. I'm fine with having only the Apache-2.0 license, but given that the commits come from CH, which is covered by both licenses, I understand it should be covered by both too.

**Comment by rbradford** [comment]
Each file in CH has an individual license. These files are Apache 2.0.

**Comment by slp** [comment]
Oh, yes, you're right. Thanks for the clarification!
